reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
reference_os: &reference_os
  'linux'
language: bash
git:
  depth: false
os:
  - *reference_os
dist: bionic
addons:
  apt:
    update: true
    packages:
      # LaTeX decent font processor
      - cm-super
      # For Minted
      - python-pygments
      # LaTeX
      - texlive-base
      - texlive-extra-utils
      - texlive-generic-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-science
      # Debug
      - tree
      # For git latexdiff
      - latexdiff
      # Image processing
      - inkscape
stages:
  - check
  - test
  - deploy
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="DanySK/gradle-latex"
  matrix:
    - *reference_jdk
#    - JDK="adopt-openj9@1.8"
#    - JDK="adopt@1.11"
#    - JDK="adopt-openj9@1.11"
#    - JDK="adopt@1.12"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - ./gradlew clean check
    - stage: deploy
      addons: true
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        # Signing
        - secure: "szQtVBImDhLKV+kR/QkODJNqRte0OvTOIYgCgf/PWCXGHJdm1BR7XBNlVktOScIKLL7y284g8oSYb5WbjulizcTQ460kvxYd1j9PtT8SWKhYPfK8xoRK3KuP0cFIn0JzrorjMS78WFHFxRE+qO8bKIevWeEY0NO9be2JA0wQX/LKsUw3Yv4TSgqSmtwCHqfzVv+t+HXD6K9wx+VONQC8PQLI1rlmV/TeMPr3XPrbtW1NaEgfRz4kKQaxPbyAXzTkWRpcJSUCwnTQ3/rONFZeSu9cXTtbIYwf/6/JOnmEGZjB5dvvAgySkv3OsAPggBsAjGPWCQVF2qdcmlmBRLvOofq6U1lfMM3PPA1FW/dx8KWOuUxgJQ3Q+1FcJvCW+wvxcHna5WW1LD8NHfvqD02SI1Ov7/RkrNfsJEp+zaE23MNziRZUnFsEOaALHwLXlYt+Vi+9qrswbUWseFL1t0ZMA+quoIZXofY1S/SSQFK75eEnpSoXHq6lMt0U0IeL9jUw7rIL94fYdiypgl5tP4Ym1dKE/UGzM+PxWwKEjr9HpKku01QJrGze1Eu3GVlJda0iovh0EH1QZw6rhQFMhvr1l3vMOWkPERABrvwQJhjEdvtRmx4YRQe+3pba4mF/tS6px62UiK0lUWSEZb8uNl58tk/wG8SzkpZt6gZVcEVwrLw="
        # Central
        - secure: "PmfoSUyVGwyxXLoODbWMLBMdsaaFD79/QwKVAlyABVqpCG+iy5xJSt7BC6y0dkz+wwXf4XhnX0dxkIMH8VbHl56K8H4BhjOUN1CoSlFmtLo78pZhCuCy1Sm5BJn6fTE+VCBGUOfA5gMHvS3wRbWGvRqri/03oIE88Atn5BGIiAcNMGT5ukClf3KYHrQ2Gk2s9Uoq1feTE4yu9j05GXythTYgpRUH7vBBoYSDf1EW1MhSfBtTRkKfkmgc3qnU8PmgPTD5OjjTMNszIg04z2zr53v5L/T6DmZmvNkfIOaLV9IJwPfPti6oMG3UPXXf7oH+jD2du8QB6NA+K6UMOVnaVrfQAQZrABa2F9Ge/2W7WOHvdQ+GMf7oYPsunTfdGfVqQtGKG6S5yHPdiwWug0DH/cgP2k2FIQXqNgfEJYikhjdZZu2GtBaBlyR0K3f1eXuhTBsZ2JJT4ctAFTap4epNIiEQJ0ASc8ZRjx8/Y0xEQh2E4SCbEgXSEEcH5c1zL/Nhls+V9lBRjWBlcVlnTIjlL8JqCz3akkkqJyFMBF8urMG3ZHY5Zg9EKylwSj6FK4VC2KngS3fzck58Rir1Eax2TQ35Ar846gPDXbHKPjer+N+5tAQFk6tfz4QQdtFnBOlJZlKhMWSpkLzzwugM60gKLwK5dIzLwGssFZdUd19UUOw="
        - secure: "HHmNQ36u6NkXYWYW61ZVTae0vAISYw6NlzxtrdigRnqJgaMpmSmaWj7Us/obk8Q1RK2jCRnFZ1vMrGR5NydjTROk8+G2gU2Po76ZtZayU4JQuWoxWQy4Cus9hkq6YijyouxjHGBaGgZcMPAjke/9QFDlK2tQB7k8cIMO7EDN2rrE9ZLokYyJ01kT7hJ+dab8+5qQGDpJRpcThi/V3ERATzHMbVnfuLgIic55EApcyxPD1562XItQPUriccxP2l+skNA0rO98JocoPUbRia2RD7PjSP4sL7pNBA9TKsbpYf5eUrU0RKo5XfsLOlMH4fSqfbKkSbaVrDxobnPu+wRXRdLa7Wcve0SOxJqboBc7aXBRzm+fcoXEfToP6BF6NbC6fzFIwOrPFRyeqVqPLWGr00Oytu4CQjRDBYjvenK8EZHTZ+BUrBx2r/C2L2Xhxl6UeFDcoTHgzqC2NsidbGZ+N3Nn/NPeqGgkgn+fjqiZX9HaSrsAlQA2WQKIkMVGsZ3QdFQsxUkFtnNh4nNCpvsj41qlag2rha0ecIWiuZieqisAS0w2lDkYvxqgeLy3Aj+ZZAq+1LD6gmdOm+9PKBOTh9vPNzwFpbf4QSyUN5Xsk4orNYNCUMpPLLJlM5J3L/9+zcdecEBPODM6LE6f+YYDB+kGkf3NmoWtsZzL+4pWQCc="
        # Plugin portal
        - secure: "Y0emT3Jfw1mUhTsycOR6yIJb+XchGQObK7NVyhWJDWZHdtST5DjgIPCd/tUKt6MbDqQ16lN3GLHV5NNU9vP1aB6ErfqN2rViVP+h1fQaUb3FnyWRmnUrttUsrLrO1r6xITY3EkMKtvnT/nndkxIjIxZ1tjR5ozaVvdnRUgLeH/ggzWMM19G/M3vAw5y/ZpNWr2OMQN3h3AzIAe5BTo9e786NuvLyQHoXEMtSihcmhKulgfID7KPAM9hSx5JweYbMiGzGOCI02fxHXjkgOtdGaVcBKlXhTV0jvo1azGCKylSM1ppIVB60d5ikbgTDzPGvuDbDaao3qi+wVf/RdOjXpbvtrgjL0CcU0LUgBKgNi7PD68URmGOnWEzfLt4Tmqr2y5YADWwBsXEhlHqHoM4O637/vSwqnpqgukaP1R6ghIFuDHU5IGEZKqzggcN+VmTb/6AnES4DCBTYr4enEmB1GPY+aKPGOzxOK7dMGEKE5/OwFgNcvN/I05gQkM1hYEDOcXH1r+lBsrdJ82cLFPE4IMmYMmzKduYXUC7iHWiHFHDpO1cFs1QQKP4wNmXipUW3o/is4Udl8HnONLK5yivWMfnV2+RPOOm0d/kGF7+0V7wtVlp2CozZJbsN3ZEPkbG7cLYuIs6hD5ZOpvrxrbnBfKideonG31EDZOcCxXEREbc="
        - secure: "Vsmc+GYLggPMGVxyvxbM0hUgOdelDysTk8JrlaBbhU9jIaKPRIvf3s6fhV1U0frDEr/7ifmnuqxKE/ByAz3BmDB0vI5gbi5Z8nvRxSC2DeTURx0zHqvlFvmCCWT3wG30kmLdskIz2wauGUqa00u79APqBU8mXdJdJLafr8iqSOnHIsotD2XN4n+mD2+MnZCguLZpPo+SGbPVrCMC+PS4/b+OeCGAIsYHt1OjmxRzmuhqx1GyZT872HR4Q/+WgDL74STwaCVeGQAZapxKKqYFrzOaZLtndoD21ZuboiK2KfaTFdUmAorSAAVsPo8jGKh44hnFo8cytEak0zKk8XXvYFmH/AlFELhKC5oVoBDrGiG11LEvXWHgTVnbPMjSNSmaUEOOY6Nan2kDNOR1iN4d11qEj4UJRV1Of1xzJCUbzdndYQAtbX7e4i4k19INh3yKz9bCctwyMyVEgNLoLFqINYiKrec8/5h8lDa07sGFX7DtwdeXZqcdDHS3WyIj+KxmA38QDlbDFoGxwmwnleWxWFQrGqfygh7zP3mY+iCuJTEygEYI2fSI4N0lUWdPnkTAVCbBabHJLoXpi50zacKcPqRGA0wO6eKybb+xn6Agn7+wHgaQhvE81tpoTgzhn1y6Cr5LRpUEIgRjKmphuA69o4JQY/xZ/6NEH8WTd9xDWIY="
        - PUBLISH="true"
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_e0634ac5d32f_key -iv $encrypted_e0634ac5d32f_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - ./gradlew sourcesJar javadocJar sign
      after_success:
        - ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET --stacktrace
        - ./gradlew publishMavenCentralPublicationToMavenRepository --stacktrace
before_install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - ./gradlew clean test --scan --parallel
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - source .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
