import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlin: String = "1.3.50"

    const val org_jetbrains_dokka: String = "0.10.0"

    const val com_uchuhimo: String = "0.20.0"

    const val org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin: String = "0.2.2"

    const val org_danilopianini_publish_on_central_gradle_plugin: String = "0.2.0"
             // available: "0.2.3"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val com_gradle_plugin_publish_gradle_plugin: String = "0.10.1"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.3.50"

    const val com_gradle_build_scan_gradle_plugin: String = "3.0"

    const val kotlintest_runner_junit5: String = "3.4.2"

    const val classgraph: String = "4.8.52"

    /**
     * Current version: "5.6.3"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
