name: CI
on:
  pull_request:

jobs:
  Build-Foreign-Pull-Request:
    if: ${{ github.event.repository.full_name != github.repository }}
    strategy:
      matrix:
        jvm_version: [8, 11, 14]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jvm_version }}
      - uses: actions/checkout@v2
      - name: Update APT
        run: sudo apt-get -y update
      - name: Install TeXLive
        run: while read package; do sudo apt-get install -y $package; done < .github/ubuntu-packages
      - shell: bash 
        run: |
          if [ -x 'build.sh' ]
          then
            echo 'Detected custom build instructions'
            ./build.sh
          elif [ -x 'gradlew' ]
          then
            echo 'Detected gradle wrapper, running ./gradlew clean check --parallel'
            ./gradlew clean check --parallel
          elif [ -f 'pom.xml' ]
          then
            echo 'Detected Maven pom.xml, running mvn clean install'
            mvn clean install
          else
            echo 'No valid configuration detected, failing'
            exit 1
          fi
